name: Build Onion Tool
on: [push]
jobs:
  BuildWindows:
    runs-on: windows-2022
    env:
      GITHUB_TOKEN: ${{secrets.ONION_GIT_PUBLIC_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - uses: lukka/get-cmake@v3.23.0
      - run: ./build_windows.bat 
