name: detached_lib
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  push:
    paths:
      - 'tests/detached_lib/**'
jobs:
  detached_lib:
    uses: ./.github/workflows/test_single.yml
    secrets: inherit
    with:
      lib: tests/detached_lib
