name: app_with_lib
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  push:
    paths:
      - 'tests/app_with_lib/**'
jobs:
  app_with_lib:
    uses: ./.github/workflows/test_single.yml
    secrets: inherit
    with:
      lib: tests/app_with_lib
