name: app_self_contained
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  push:
    paths:
      - 'tests/app_self_contained/**'
jobs:
  app_self_contained:
    uses: ./.github/workflows/test_single.yml
    secrets: inherit
    with:
      lib: tests/app_self_contained
