name: module_with_static_lib
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
  push:
    paths:
      - 'tests/module_with_static_lib/**'
jobs:
  module_with_static_lib:
    uses: ./.github/workflows/test_single.yml
    secrets: inherit
    with:
      lib: tests/module_with_static_lib
